font:
  # The normal (roman) font face to use.
  size: 8.0
  normal:
    # family: Droid Sans Mono Slashed for Powerline
    family: Monospace
    # family: iosevka
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    # family: iosevka
    family: Monospace
    # family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: iosevka
    # family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    # style: Italic

# Colors (Nord)
colors:
   # Default colors
   primary:
     background: '0x2E3440'
     foreground: '0xD8DEE9'

   selection:
     text: '0x292d3e'
     background: '0xbbc5ff'

   # Normal colors
   normal:
     black:   '0x3B4252'
     red:     '0xBF616A'
     green:   '0xA3BE8C'
     yellow:  '0xEBCB8B'
     blue:    '0x81A1C1'
     magenta: '0xB48EAD'
     cyan:    '0x88C0D0'
     white:   '0xE5E9F0'

   # Bright colors
   bright:
     black:   '0x4C566A'
     red:     '0xBF616A'
     green:   '0xA3BE8C'
     yellow:  '0xEBCB8B'
     blue:    '0x81A1C1'
     magenta: '0xB48EAD'
     cyan:    '0x8FBCBB'
     white:   '0xECEFF4'

    # colors:
    #   # Default colors
    #   primary:
    #     background: '0x0a0f14'
    #     foreground: '0x98d1ce'
    # 
    #   # Normal colors
    #   normal:
    #     black:   '0x0a0f14'
    #     red:     '0xc33027'
    #     green:   '0x26a98b'
    #     yellow:  '0xedb54b'
    #     blue:    '0x195465'
    #     magenta: '0x4e5165'
    #     cyan:    '0x33859d'
    #     white:   '0x98d1ce'
    # 
    #   # Bright colors
    #   bright:
    #     black:   '0x10151b'
    #     red:     '0xd26939'
    #     green:   '0x081f2d'
    #     yellow:  '0x245361'
    #     blue:    '0x093748'
    #     magenta: '0x888ba5'
    #     cyan:    '0x599caa'
    #     white:   '0xd3ebe9'

# shell:
#   program: /usr/bin/tmux
#   args:
#     - -u # force UTF-8 in tmux

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Values for `animation`:
#   - Ease
#   - EaseOut
#   - EaseOutSine
#   - EaseOutQuad
#   - EaseOutCubic
#   - EaseOutQuart
#   - EaseOutQuint
#   - EaseOutExpo
#   - EaseOutCirc
#   - Linear
#


env:
  TERM: xterm-256color

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  #dimensions:
  #  columns: 0
  #  lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 6
    y: 6

  # Spread additional padding evenly around the terminal content.
  #dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  #decorations: full

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  #startup_mode: Windowed

  # Window title
  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark` and `light`.
  # Set this to `None` to use the default theme variant.
  #gtk_theme_variant: None


scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  #multiplier: 3

  # Scroll to the bottom when new text is written to the terminal.
  #auto_scroll: false

# Spaces per Tab (changes require restart)
#
# This setting defines the width of a tab in cells.
#
# Some applications, like Emacs, rely on knowing about the width of a tab.
# To prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
#tabspaces: 8

background_opacity: 1.0
# background_opacity: 0.95

