-- require('rust-tools').setup {
--     tools = {
--         autoSetHints = false,
--         hover_with_actions = false,
--         runnables = {use_telescope = false},
--         inlay_hints = {
--             parameter_hints_prefix = "» ",
--             other_hints_prefix = "« "
--         },
--         hover_actions = {auto_focus = false}
--     },
--     server = {
--       on_attach = on_attach,
--       flags = {debounce_text_changes = 150}
--     }
-- }
